apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bsrn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bsrn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0045-app
  name: devfile-sample-bsrn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bsrn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bsrn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0045-tenant/tkrw-pr714-0075-0045-app/devfile-sample-bsrn@sha256:7ab956b0898ee25698f51f800e56f2f54217e7bde8f47772dca9f6081fcf9faf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
